stderr > Given error: [Function (anonymous)]
Given error: [Function (anonymous)]
Given error: Error: Expected 1 errors, got 0
    at Then.thenCB (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/src/lib/BaseSuite.test.mjs:252:15)
    at file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:425:29
    at Object.butThen (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/src/lib/BaseSuite.test.mjs:290:55)
    at Then.butThen (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:749:42)
    at Then.test (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:420:17)
    at Given.give (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:351:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Testeranto.constructor.run (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:242:20)
    at async file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:531:19
    at async Object.receiveTestResourceConfig (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:559:29)
goodbye node with caught error Error: Expected 1 errors, got 0
    at Then.thenCB (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/src/lib/BaseSuite.test.mjs:252:15)
    at file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:425:29
    at Object.butThen (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/src/lib/BaseSuite.test.mjs:290:55)
    at Then.butThen (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:749:42)
    at Then.test (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:420:17)
    at Given.give (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:351:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Testeranto.constructor.run (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:242:20)
    at async file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:531:19
    at async Object.receiveTestResourceConfig (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:559:29)
stdout > test failed 3 Error: Expected 1 errors, got 0
    at Then.thenCB (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/src/lib/BaseSuite.test.mjs:252:15)
    at file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:425:29
    at Object.butThen (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/src/lib/BaseSuite.test.mjs:290:55)
    at Then.butThen (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:749:42)
    at Then.test (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:420:17)
    at Given.give (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:351:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Testeranto.constructor.run (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:242:20)
    at async file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:531:19
    at async Object.receiveTestResourceConfig (file:///Users/adam/Code/testeranto/testeranto/bundles/node/allTests/chunk-4PJCC2XT.mjs:559:29)
